name: publish

on:
  release:
    types: [ published, edited ]

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: publish
    if: ${{ github.repository_owner == 'wamra' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: '@wamra'
          always-auth: true

      - name: Setup .npmrc
        run : echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Verify npm authentication
        run: npm whoami

      - name: Install dependencies
        run: |
          if [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Dry-run Publish
        run: npm publish --dry-run

      - name: NPM Publish
        run: npm publish --access public
